"""empty message

Revision ID: 9029ac412f7f
Revises: 0b3385b7216a
Create Date: 2021-05-12 14:54:40.681815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9029ac412f7f'
down_revision = '0b3385b7216a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###
